# Content-Based Filtering

Imports and making artist column a column of lists

In [82]:
import pandas as pd
df = pd.read_csv('proc.csv')

#Convert artists to list of artists
df['artists'] = df['artists'].astype(str)
df['artists'] = df['artists'].apply(lambda x: x.split(';'))
df.head()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,3nqQXoyQOWXiESFLlDF1hG,"[Sam_Smith, Kim_Petras]",Unholy (feat. Kim Petras),Unholy (feat. Kim Petras),100,156943,False,0.714,0.472,2,-7.375,1,0.0864,0.01300,0.000005,0.2660,0.238,131.121,4,dance
1,2tTmW7RDtMQtBk7m2rYeSw,"[Bizarrap, Quevedo]","Quevedo: Bzrp Music Sessions, Vol. 52","Quevedo: Bzrp Music Sessions, Vol. 52",99,198937,False,0.621,0.782,2,-5.548,1,0.0440,0.01250,0.033000,0.2300,0.550,128.033,4,hip-hop
2,4uUG5RXrOk84mYEfFvj3cK,"[David_Guetta, Bebe_Rexha]",I'm Good (Blue),I'm Good (Blue),98,175238,True,0.561,0.965,7,-3.673,0,0.0343,0.00383,0.000007,0.3710,0.304,128.040,4,dance
3,5ww2BF9slyYgNOk37BlC4u,[Manuel_Turizo],La Bachata,La Bachata,98,162637,False,0.835,0.679,7,-5.329,0,0.0364,0.58300,0.000002,0.2180,0.850,124.980,4,latin
4,6Sq7ltF9Qa7SNFBsV5Cogx,"[Bad_Bunny, Chencho_Corleone]",Un Verano Sin Ti,Me Porto Bonito,97,178567,True,0.911,0.712,1,-5.105,0,0.0817,0.09010,0.000027,0.0933,0.425,92.005,4,latin

Selecting useful columns

In [83]:
df = df[['track_id', 'artists', 'track_name', 'popularity', 'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo', 'track_genre']]
df.head()

,track_id,artists,track_name,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,track_genre
0,3nqQXoyQOWXiESFLlDF1hG,"[Sam_Smith, Kim_Petras]",Unholy (feat. Kim Petras),100,0.714,0.472,2,-7.375,1,0.0864,0.01300,0.000005,0.2660,0.238,131.121,dance
1,2tTmW7RDtMQtBk7m2rYeSw,"[Bizarrap, Quevedo]","Quevedo: Bzrp Music Sessions, Vol. 52",99,0.621,0.782,2,-5.548,1,0.0440,0.01250,0.033000,0.2300,0.550,128.033,hip-hop
2,4uUG5RXrOk84mYEfFvj3cK,"[David_Guetta, Bebe_Rexha]",I'm Good (Blue),98,0.561,0.965,7,-3.673,0,0.0343,0.00383,0.000007,0.3710,0.304,128.040,dance
3,5ww2BF9slyYgNOk37BlC4u,[Manuel_Turizo],La Bachata,98,0.835,0.679,7,-5.329,0,0.0364,0.58300,0.000002,0.2180,0.850,124.980,latin
4,6Sq7ltF9Qa7SNFBsV5Cogx,"[Bad_Bunny, Chencho_Corleone]",Me Porto Bonito,97,0.911,0.712,1,-5.105,0,0.0817,0.09010,0.000027,0.0933,0.425,92.005,latin

One Hot Encoding

In [84]:
def ohe(df, column, name):
    idf = pd.get_dummies(df[column])
    features = idf.columns
    idf.columns = [name + "|" + str(i) for i in features]
    idf.reset_index(drop = True, inplace = True)
    return idf

Encoding Key

In [85]:
key_encoded = ohe(df, 'key', 'key') * 0.25
key_encoded.head()

,key|0,key|1,key|2,key|3,key|4,key|5,key|6,key|7,key|8,key|9,key|10,key|11
0,0.0,0.00,0.25,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0
1,0.0,0.00,0.25,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0
2,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.25,0.0,0.0,0.0,0.0
3,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.25,0.0,0.0,0.0,0.0
4,0.0,0.25,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0

Encoding Mode

In [86]:
mode_encoded = ohe(df, 'mode', 'mode') * 0.25
mode_encoded.head()

   mode|0  mode|1
0    0.00    0.25
1    0.00    0.25
2    0.25    0.00
3    0.25    0.00
4    0.25    0.00

Encoding Genre

In [87]:
genre_encoded = ohe(df, 'track_genre', 'track_genre') * 0.5
genre_encoded.head()

,track_genre|acoustic,track_genre|afrobeat,track_genre|alt-rock,track_genre|alternative,track_genre|ambient,track_genre|anime,track_genre|bluegrass,track_genre|blues,track_genre|brazil,track_genre|breakbeat,...,track_genre|sleep,track_genre|soul,track_genre|spanish,track_genre|swedish,track_genre|synth-pop,track_genre|techno,track_genre|trance,track_genre|trip-hop,track_genre|turkish,track_genre|world-music
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Scaling Popularity between 0-1

In [88]:
from sklearn.preprocessing import MinMaxScaler

pop = df[['popularity']].reset_index(drop = True)
scaler = MinMaxScaler()

spop = pd.DataFrame(scaler.fit_transform(pop), columns=pop.columns)
spop.head()

   popularity
0        1.00
1        0.99
2        0.98
3        0.98
4        0.97

Calculating tf-idf score of each artist to determine artist prevalance in a song

In [89]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

#Convert artist list to tfidf-matrix of artists
tfidf_mat = tfidf.fit_transform(df['artists'].apply(lambda x: " ".join(x)))

#Make the tfidf matrix its own dataframe
art_df = pd.DataFrame(tfidf_mat.toarray())
art_df.columns = ['artist | ' + i for i in tfidf.get_feature_names_out()]

#Reset index
art_df.reset_index(drop = True, inplace = True)
art_df.head()

,artist | 070_shake,artist | 10_years,artist | 10cc,artist | 10cm,artist | 11,artist | 112,artist | 11_music_group,artist | 12_stones,artist | 182,artist | 1991,...,artist | 理想混蛋,artist | 理想混蛋_雞丁,artist | 美波,artist | 艾薇,artist | 詹雯婷,artist | 鈴木愛理,artist | 阿涵,artist | 陳卓賢_ian,artist | 須田景凪,artist | 高爾宣_osn
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Creating final feature dataframe

In [90]:
final = pd.concat([art_df, spop, genre_encoded, mode_encoded, key_encoded], axis=1)
final['track_id'] = df['track_id'].values
final.head()

,artist | 070_shake,artist | 10_years,artist | 10cc,artist | 10cm,artist | 11,artist | 112,artist | 11_music_group,artist | 12_stones,artist | 182,artist | 1991,...,key|3,key|4,key|5,key|6,key|7,key|8,key|9,key|10,key|11,track_id
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,3nqQXoyQOWXiESFLlDF1hG
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,2tTmW7RDtMQtBk7m2rYeSw
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.25,0.0,0.0,0.0,0.0,4uUG5RXrOk84mYEfFvj3cK
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.25,0.0,0.0,0.0,0.0,5ww2BF9slyYgNOk37BlC4u
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,6Sq7ltF9Qa7SNFBsV5Cogx

Processing playlist dataframe

In [91]:
playlist_df = pd.read_csv('playlist.csv')
playlist_df = select_columns(playlist_df)
playlist_df['artists'] = playlist_df['artists'].apply(lambda x: x.split(';'))

Converting playlist dataframe to its own vector, removing all playlist songs from final feature dataframe

In [92]:
def playlist_features(feature_set, df):
    #Vector
    #add all tracks that are both in the playlist and final df 
    playlist_feature_set = feature_set[feature_set['track_id'].isin(df['track_id'].values)]
    
    #Drop track id column and sum all values in a column, convert to one vector
    playlist_feature_set = playlist_feature_set.drop(columns = 'track_id')
    playlist_vector = playlist_feature_set.sum(axis=0)
    
    #Song dataframe without any songs already in playlist 
    comparison_frame = feature_set[~feature_set['track_id'].isin(df['track_id'].values)] #Don't include tracks already in playlist
    
    return playlist_vector, comparison_frame

playlist_vector, comparison_frame = playlist_features(final, playlist_df)

Run cosine similarity algorithm between all dataframe songs and the playlist vector

In [93]:
from sklearn.metrics.pairwise import cosine_similarity
#Trim out all playlist songs from main dataframe 
recommendation = df[df['track_id'].isin(comparison_frame['track_id'].values)] 

#Go through each song in the dataframe and calculate similarity score with playlist vector
recommendation['sim'] = cosine_similarity(comparison_frame.drop('track_id', axis=1).values, playlist_vector.values.reshape(1,-1))[:,0]

C:\Users\tilak\AppData\Local\Temp\ipykernel_2008\262382816.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recommendation['sim'] = cosine_similarity(comparison_frame.drop('track_id', axis=1).values, playlist_vector.values.reshape(1,-1))[:,0]

Return rec

In [94]:
top_100 = recommendation.sort_values('sim', ascending=False).head(100)
top_100.to_csv('./recommendations.csv')
top_100.head()

,track_id,artists,track_name,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,track_genre,sim
189,3GZD6HmiNUhxXYf8Gch723,[Frank_Ocean],Lost,85,0.913,0.6030,8,-4.892,1,0.2260,0.0272,0.000503,0.167,0.497,123.061,soul,0.703773
751,6Nle9hKrkL1wQpwNfEkxjh,[Frank_Ocean],Chanel,79,0.776,0.5030,0,-5.732,0,0.2370,0.8740,0.000000,0.112,0.473,110.134,soul,0.690113
499,4osgfFTICMkcGbbigdsa53,[Frank_Ocean],Novacane,81,0.762,0.5080,3,-9.112,1,0.0919,0.0584,0.001260,0.160,0.370,93.510,soul,0.688019
753,2LMkwUfqC6S6s6qDVlEuzV,[Frank_Ocean],White Ferrari,79,0.501,0.0958,0,-15.605,1,0.0433,0.7700,0.000000,0.298,0.204,108.741,soul,0.682622
2052,4QhWbupniDd44EDtnh2bFJ,[Frank_Ocean],Pyramids,73,0.400,0.6500,5,-6.104,0,0.0466,0.0118,0.000076,0.791,0.150,107.989,soul,0.680665